# Generated by Django 2.1.2 on 2018-10-17 10:44

from django.db import migrations, models
import flightBot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('message_id', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=10, validators=[flightBot.models.validate_dialog_source])),
                ('content', models.TextField(default='')),
                ('response_params', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
