# Generated by Django 2.1.2 on 2018-10-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='source_type',
            new_name='source',
        ),
    ]
